name: flutter_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  hive_flutter: ^1.0.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  url_launcher: ^6.0.6
  webview_flutter: ^2.1.1
  injectable: ^1.4.0
  get_it: ^7.1.3
  freezed_annotation: ^2.0.3
  cupertino_icons: ^1.0.3
  vrouter: ^1.1.4+15
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.1.0
  firebase_messaging_platform_interface: ^3.0.9
  firebase_messaging_web: ^2.1.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.0
  equatable: ^2.0.3
  connectivity_plus: ^2.2.1
  chopper: ^4.0.1
  flutter_local_notifications: ^9.4.0
  move_to_background: ^1.0.2
  flutter_snake_navigationbar: ^0.6.1
  percent_indicator: ^4.0.0
  dotted_decoration: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  qr_flutter: ^4.0.0
  jwt_decoder: ^2.0.1
  flutter_portal: ^0.4.0
  fluttertoast: ^8.0.8
  uni_links: ^0.5.1
  permission_handler: ^9.2.0
  path_provider: ^2.0.0
  flutter_downloader: ^1.7.0
  flutter_html: ^3.0.0-alpha.2
  #qr_code_scanner: ^0.7.0
  flutter_stripe: ^3.1.0
  pay: ^1.0.5
  file_picker: ^4.1.4
  camera: ^0.9.4+2
  pull_to_refresh: ^2.0.0
  app_settings: ^4.1.1
  dartz: ^0.10.0
  excel:
  flutter_paypal: ^0.0.8
  flutter_keyboard_visibility: ^5.2.0
  masked_text_field: ^1.0.0
  http: ^0.13.4
  firebase_remote_config: ^2.0.8
  firebase_analytics: ^9.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mockito: ^5.0.10
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4
  freezed: ^2.0.3+1
  chopper_generator: ^4.0.1
  local_auth: ^1.1.11

#dependency_overrides:
#  firebase_messaging_platform_interface: 3.1.6
#  firebase_crashlytics_platform_interface: 3.1.13
#  cloud_firestore_platform_interface: 5.4.13
#  firebase_auth_platform_interface: 6.1.11
#  firebase_storage_platform_interface: 4.0.14
#  cloud_functions_platform_interface: 5.0.21
#  firebase_analytics_platform_interface: 3.0.5
#  firebase_remote_config_platform_interface: 1.0.5
#  firebase_dynamic_links_platform_interface: 0.2.0+5
#  firebase_performance_platform_interface: 0.1.0+5
#  firebase_app_installations_platform_interface: 0.1.0+6

flutter:
#  plugin:
#    platforms:
#      android:
#        package: io.flutter.plugins.firebase.messaging
#        pluginClass: FlutterFirebaseMessagingPlugin
#      ios:
#        pluginClass: FLTFirebaseMessagingPlugin
#      macos:
#        pluginClass: FLTFirebaseMessagingPlugin
#      web:
#        default_package: firebase_messaging_web
  uses-material-design: true

  assets:
    - img/
    - assets/spinner.gif
    - assets/apple_pay_payment_profile.json
    - assets/google_pay_payment_profile.json
    - assets/form_basic_registration.json
